<template>
  <va-button-group
    class="mb-6"
    size="large"
  >
    <va-button>L1</va-button>
    <va-button>L2</va-button>
    <va-button>L3</va-button>
  </va-button-group>

  <va-button-group
    class="mb-6"
    size="small"
  >
    <va-button>One</va-button>
    <va-button>Two</va-button>
    <va-button>Three</va-button>
  </va-button-group>
</template>
