<template>
  <div>
    <va-button-dropdown
      disabled
      label="disabled"
    >
      Content
    </va-button-dropdown>
    <va-button-dropdown
      split
      disable-button
      label="disable-button"
    >
      Content
    </va-button-dropdown>
    <va-button-dropdown
      split
      disable-dropdown
      label="disable-dropdown"
    >
      Content
    </va-button-dropdown>
  </div>
</template>
