<template>
  <div>
    <va-badge
      text="3"
      overlap
      class="mr-2"
    >
      <va-avatar src="https://randomuser.me/api/portraits/women/5.jpg"/>
    </va-badge>
    <va-badge
      dot
    >
      <va-avatar
        square
        src="https://randomuser.me/api/portraits/women/8.jpg"
      />
    </va-badge>
  </div>
</template>
