export const variables = [
  'display',
  'justifyContent',
  'alignItems',
  'backgroundImage',
  'boxShadow',
  'borderWidth',
  'borderColor',
  'borderStyle',
  'fontWeight',
  'transition',
  'padding',
  'cursor',
  'size',
  'contentPy',
  'contentPx',
  'onlyIconContentPx',
  'fontSize',
  'letterSpacing',
  'lineHeight',
  'borderRadius',
  'iconsSpacing',
  'iconSidePadding',
  'borderedBorder',
  'borderedStyle',
] as const
