<template>
  <div class="flex items-center flex-col gap-2 sm:flex-row">
    <VaButton
      icon="clear"
      color="danger"
    >
      Delete
    </VaButton>
    <VaButton
      icon-right="arrow_forward"
      icon-color="#ffffff50"
    >
      Continue
    </VaButton>
    <VaButton
      icon="add"
      color="warning"
      icon-color="#812E9E"
    />
    <VaButton
      icon="star"
      icon-right="unfold_more"
    />
  </div>
</template>
