<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
    <va-button
      icon="clear"
      color="danger"
    >
      Delete
    </va-button>
    <va-button
      icon-right="arrow_forward"
      icon-color="#ffffff50"
    >
      Continue
    </va-button>
    <va-button
      icon="add"
      color="warning"
      icon-color="#812E9E"
    />
    <va-button
      icon="star"
      icon-right="unfold_more"
    />
  </div>
</template>
