<template>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 items-start">
    <va-image
      class="col-span-1"
      :ratio="16/9"
      src="https://picsum.photos/1500"
    />
    <va-image
      class="col-span-1"
      :ratio="4/3"
      src="https://picsum.photos/1500"
    />
    <va-image
      class="col-span-1"
      :ratio="1"
      src="https://picsum.photos/1500"
    />
  </div>
</template>
