import './components/vuestic-sass/resources/_css-variables.scss'
export { VuesticPlugin } from './components/vuestic-plugin'
export { useColor } from './services/color-config/ColorMixin'
export { useGlobalConfig } from './services/GlobalConfigPlugin'
export { setupColors as useTheme } from './services/color-config/color-config'
