<template>
  <div class="relative">
    <va-app-bar color="danger">
      <va-button
        icon="home"
        color="#fff"
        preset="plain"
      />
      <va-button
        icon="info"
        color="#fff"
        preset="plain"
      />
      <va-button
        icon="battery"
        color="#fff"
        preset="plain"
      />
      <va-spacer />
      <va-button
        color="#fff"
        preset="plain"
      >
        Login
      </va-button>
      <va-button-dropdown
        preset="plain"
        color="secondary"
        icon-color="#fff"
      >
        Content
      </va-button-dropdown>
    </va-app-bar>
  </div>

  <div
    class="mt-2 relative"
  >
    <va-app-bar
      color="info"
      gradient
    >
      <va-button
        icon="home"
        color="#fff"
        preset="plain"
      />
      <va-button
        icon="info"
        color="#fff"
        preset="plain"
      />
      <va-button
        icon="battery"
        color="#fff"
        preset="plain"
      />
      <va-spacer />
      <va-button
        color="#fff"
        preset="plain"
      >
        Login
      </va-button>
      <va-button-dropdown
        preset="plain"
        color="secondary"
        icon-color="#fff"
      >
        Content
      </va-button-dropdown>
    </va-app-bar>
  </div>
</template>
