<template>
  <va-button-dropdown
    class="mr-2 mb-2"
    color="warning"
    textColor="danger"
    label="warning&gradient"
    gradient
  >
    Content
  </va-button-dropdown>
  <va-button-dropdown
    class="mr-2 mb-2"
    color="danger"
    label="danger"
  >
    Content
  </va-button-dropdown>
  <va-button-dropdown
    class="mr-2 mb-2"
    preset="primary"
    color="#525252"
    label="#525252"
    split
  >
    Content
  </va-button-dropdown>
  <va-button-dropdown
    preset="secondary"
    color="warning"
    label="warning"
    split
  >
    Content
  </va-button-dropdown>
  <va-button-dropdown
    preset="plain"
    color="success"
    label="success"
    split
  >
    Content
  </va-button-dropdown>
</template>
